{{- if (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clickhouse-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: clickhouse-operator
spec:
  selector:
    matchLabels:
      clickhouse.radondb.com/app: chop
  endpoints:
    - interval: 10s
      path: /metrics
      port: clickhouse-metrics
  namespaceSelector:
    any: true
  {{- end }}