---

- import_tasks: precheck.yaml

- name: KubeSphere | Checking KubeSphere component
  shell: >
    {{ bin_dir }}/kubectl get deploy -n kubesphere-system
  register: kubesphere_component_deployment


- import_tasks: helm-migrate.yaml
  when:
    - kubesphere_component_deployment.stdout.find("ks-console") != -1
