---

- hosts: localhost
  gather_facts: false
  roles:
    - kubesphere-defaults
    - role: dmp
      when:
        - "status.dmp is not defined or status.dmp.status is not defined or status.dmp.status != 'enabled'"

